name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ilammy/setup-nasm@v1
    - uses: actions/checkout@v4
    - name: make
      run: make
